### ISSUE TITLE
默认加载人格无法使用

### ISSUE THREAD

**Issue by lumineyuri** [wangyu1997/GsChat#2]
已经确定有文件 但是使用NormalChat依然没有自动加载

**Comment by wangyu1997** [comment]
贴一下log

**Comment by lumineyuri** [comment]
```
05-14 17:32:27 [INFO] gsuid_core.bot | [发送消息to] onebot - group - 46078xxx
05-14 17:32:37 [INFO] gsuid_core.handler | [Raw] raw_text=切换引擎bing, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=936xxx, msg_id=-4263xxxx, user_type=group, group_id=4xxxxx4, user_id=59xxxx2, user_pm=3, content=[Message(type='text', data='切换引擎bing')],
05-14 17:32:37 [INFO] gsuid_core.handler | [Trigger] 消息 「切换引擎bing」 触发 「prefix」 类型触发器, 关键词: 「切换引 擎」
05-14 17:32:37 [INFO] gsuid_core.handler | [Command] command=切换引擎, text=bing
05-14 17:32:37 [INFO] gsuid_core.bot | [发送消息to] onebot - group - 4607xxx
05-14 17:32:40 [INFO] gsuid_core.handler | [Raw] raw_text=切换引擎chat, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=936xx76, msg_id=1442xxx39, user_type=group, group_id=460xxxx, user_id=599xxx, user_pm=3, content=[Message(type='text', data='切换引擎chat')],
05-14 17:32:40 [INFO] gsuid_core.handler | [Trigger] 消息 「切换引擎chat」 触发 「prefix」 类型触发器, 关键词: 「切换引 擎」
05-14 17:32:40 [INFO] gsuid_core.handler | [Command] command=切换引擎, text=chat
05-14 17:32:40 [INFO] gsuid_core.bot | [发送消息to] onebot - group - 460xxx
```

**Comment by lumineyuri** [comment]
另外还出现了另外一个问题 发病无法使用
```
05-14 17:47:14 [INFO] gsuid_core.handler | [Trigger] 消息 「发病黑塔」 触发 「prefix」 类型触发器, 关键词: 「发病」
05-14 17:47:14 [INFO] gsuid_core.handler | [Command] command=发病, text=黑塔
Task exception was never retrieved
future: <Task finished name='Task-40616' coro=<setereo_handle() done, defined at D:\Bot\gsuid_core\gsuid_core\plugins\gsuidcore_plugin_chat\gsuidcore_plugin_chat\gs_other.py:31> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "D:\Bot\gsuid_core\gsuid_core\plugins\gsuidcore_plugin_chat\gsuidcore_plugin_chat\gs_other.py", line 39, in setereo_handle
    await bot.send(await setereo.get_setereo(text))
  File "D:\Bot\gsuid_core\gsuid_core\plugins\gsuidcore_plugin_chat\gsuidcore_plugin_chat\others\setereo.py", line 40, in get_setereo
    msg = random.choice(self.datas).format(target_name=name)
  File "C:\Users\Miku\AppData\Local\Programs\Python\Python39\lib\random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

```

**Comment by wangyu1997** [comment]
第一个问题：这里切换引擎是不会加载人格的，只有当发送消息触发了new Bot的时候才会加载 你可以观察创建新会话时候的Log
第二个问题：建议截图GsChat的data目录和config的Setereo部分，并确保setereo.data存在，目前没有测试过在windows上运行会不会产生乱码，之前有水友反应过，自己修改了文件加载成功了

**Comment by lumineyuri** [comment]
> 第一个问题：这里切换引擎是不会加载人格的，只有当发送消息触发了new Bot的时候才会加载 你可以观察创建新会话时候的Log 第二个问题：建议截图GsChat的data目录和config的Setereo部分，并确保setereo.data存在，目前没有测试过在windows上运行会不会产生乱码，之前有水友反应过，自己修改了文件加载成功了

我可能发现问题所在了 在仔细看了log之后发现不能加载的文件都出现了
```
05-14 20:44:18    self._target(*self._args, **self._kwargs)
  File "D:\Bot\gsuid_core\gsuid_core\plugins\gsuidcore_plugin_chat\gsuidcore_plugin_chat\others\setereo.py", line 24, in <lambda>
    target=lambda: asyncio.run(self.init_data()), daemon=True
  File "C:\Users\Miku\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Miku\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Bot\gsuid_core\gsuid_core\plugins\gsuidcore_plugin_chat\gsuidcore_plugin_chat\others\setereo.py", line 37, in init_data
    self.datas = open(self.data_file, 'r').readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: illegal multibyte sequence
```
文件是UTF-8的 但是程序试图使用GBK编码读取

**Comment by lumineyuri** [comment]
在我把加载代码修改成为
`self.datas = open(self.data_file, 'r', encoding='utf-8').readlines()`
时错误消失了

**Comment by wangyu1997** [comment]
感谢，马上修复

**Comment by wangyu1997** [comment]
已修复
